import {
  pgTable,
  text,
  uuid,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";
import { questionsTable } from "./questions";

export const assetsTable = pgTable("assets", {
  id: uuid("id").primaryKey().defaultRandom(),
  questionId: uuid("question_id")
    .notNull()
    .references(() => questionsTable.id, { onDelete: "cascade" }),
  type: varchar("type", { length: 50 }).notNull(), // 'diagram', 'graph', 'structure', etc.
  url: text("url").notNull(),
  altText: text("alt_text"),
  latexCode: text("latex_code"), // Generated by Vision LLM
  description: text("description"), // AI generated description
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export type Asset = typeof assetsTable.$inferSelect;
export type InsertAsset = typeof assetsTable.$inferInsert;
